import{i as l,S as m}from"./assets/vendor-5b791d57.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const a of i.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function s(t){if(t.ep)return;t.ep=!0;const i=o(t);fetch(t.href,i)}})();class g{constructor(){this.BASE_URL="https://pixabay.com/api/",this.KEY="?key=42244518-9742bcd26a7acdceb08ce98f6"}getImages(e){this.PARAMS=`&q=${e}&image_type=photo&orientation=horizontal&safesearch=true`;const o=this.BASE_URL+this.KEY+this.PARAMS;return fetch(o).then(s=>s.json()).then(s=>{if(s.hits&&s.hits.length>0)return s.hits;l.error({message:"Sorry, there are no images matching your search query. Please try again!",titleColor:"white",titleSize:"16px",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",iconUrl:"/img/error.svg",iconColor:"white",position:"topRight",maxWidth:"432px"})}).catch(s=>{console.error("Fetch error:",s)})}}const u={imageElem:document.querySelector(".gallery")};function p({webformatURL:r,largeImageURL:e,tags:o,likes:s,views:t,comments:i,downloads:a}){return`
    <li class="gallery-item">
        <a href="${e}">
            <img src="${r}" alt="${o}""/>
            <div class="img-info">
                <p class="info-item"><b>Likes:</b>${s}</p>
                <p class="info-item"><b>Views:</b>${t}</p>
                <p class="info-item"><b>Comments:</b>${i}</p>
                <p class="info-item"><b>Downloads:</b>${a}</p>
            </div>
        </a>
    </li>
    `}function f(r){return r.map(p).join("")}function h(r){const e=f(r);u.imageElem.innerHTML=e,new m(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt"}).refresh()}const c="image-tag",n={imgTagInput:document.querySelector("#search-img"),searchBtn:document.querySelector(".form"),loader:document.querySelector(".backdrop")};n.imgTagInput.addEventListener("input",y);n.searchBtn.addEventListener("submit",S);const d=new g;function y(){const e={tag:n.imgTagInput.value.trim()};I(c,e)}function S(r){r.preventDefault();const e=n.imgTagInput.value.trim();e===""?l.error({message:"Please enter a search tag",titleColor:"white",titleSize:"16px",messageColor:"white",messageSize:"16px",backgroundColor:"#ef4040",iconUrl:"img/error.svg",iconColor:"white",position:"topRight"}):(n.loader.classList.add("is-open"),d.getImages(e).then(o=>h(o)).catch(o=>{console.log(o)}).finally(()=>{n.loader.classList.remove("is-open")})),localStorage.removeItem(c),n.searchBtn.reset()}function I(r,e){const o=JSON.stringify(e);localStorage.setItem(r,o)}function b(r){const e=localStorage.getItem(r);try{return JSON.parse(e)}catch(o){return console.error("Error parsing JSON from localStorage:",o),{}}}function v(){const r=b(c)||{};n.imgTagInput.value=r.tag||""}v();
//# sourceMappingURL=commonHelpers.js.map
